variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - dataset.zip
    - wavlm/WavLM-Large.pt

useGPU:
    image: nvcr.io/nvidia/pytorch:24.08-py3
    stage: build
    tags:
        - saas-linux-medium-amd64-gpu-standard
    script:
        - echo "Check whether we have enabled our GPU or not."
        - python3 -c "import torch; print(torch.cuda.is_available())"
        - pip install -r requirements.txt
        - wget -O dataset.zip "https://vctk.creativec.eu/dataset-two-speakers.zip" || [[ $? -eq 1 ]]
        - ./prepare.sh
        - time python3 convert.py --hpfile logs/freevc/config.json --ptfile logs/freevc/G_0.pth --txtpath convert.txt --outdir outputs/freevc
    artifacts:
      paths:
        - logs/freevc/*.pth
