variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - dataset.zip
    - wavlm/WavLM-Large.pt

useGPU:
    image: nvcr.io/nvidia/pytorch:24.08-py3
    stage: build
    tags:
        - saas-linux-medium-amd64-gpu-standard
    script:
        - echo "Check whether we have enabled our GPU or not."
        - python3 -c "import torch; print(torch.cuda.is_available())"
        - pip install -r requirements.txt
        - wget -nc -O dataset.zip "https://pers.creativec.eu/VCTK-Corpus-sample.zip" || [[ $? -eq 1 ]]
        - ./prepare.sh
