useGPU:
    image: nvcr.io/nvidia/pytorch:24.08-py3
    stage: build
    tags:
        - saas-linux-medium-amd64-gpu-standard
    script:
        - echo "Check whether we have enabled our GPU or not."
        - python3 -c "import torch; print(torch.cuda.is_available())"
        - pip install -r requirements.txt
        - ./prepare.sh
