useGPU:
    image: pytorch/pytorch:latest
    stage: build
    tags:
        - linux_x64
    script:
        - echo "Check whether we have enabled our GPU or not."
        - nvidia-smi
        - python3 -c "import torch; print(torch.cuda.is_available())"
